language: php

php:
  7.1.9

install:
  - composer install
  - composer dump -o

cache:
  directories:
  - vendor

script:
  ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls4