language: php

php:
  - 8.0

services:
  - mysql

install:
  - composer require consolidation/robo:2.*
  - composer install
  - composer update
  - composer dump -o
  - ./vendor/bin/robo creat:tmp-dir
  - composer require phpunit/phpunit

cache:
  directories:
  - vendor

script:
 - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml


after_success:
  - composer require php-coveralls/php-coveralls
  - travis_retry php vendor/bin/php-coveralls