language: php

php:
  - 8.2

env:
    global:
        - XDEBUG_MODE=coverage

services:
  - mysql

install:
  - composer install
  - composer update
  - composer dump -o
  - composer require phpunit/phpunit

cache:
  directories:
  - vendor

script:
 - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml


after_success:
  - composer require php-coveralls/php-coveralls
  - travis_retry php vendor/bin/php-coveralls