language: php

php:
  - nightly

install:
  - composer install
  - composer dump -o

cache:
  directories:
  - vendor

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_succes:
  travis_retry php vendor/bin/php-coveralls